version: "3.9"
services:
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    container_name: ctuexchangedb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ctuexchange
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

volumes:
  db_data: