version: "3.9"
services:
  backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://ctuexchangedb/ctuexchange"
      - "SPRING_DATASOURCE_USERNAME=user"
      - "SPRING_DATASOURCE_PASSWORD=password"
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    container_name: ctuexchangedb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ctuexchange
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

volumes:
  db_data: